### ISSUE TITLE
Setting ConfigServer does not effect 

### ISSUE THREAD

**Issue by Pamir** [microsoft/azure-spring-cloud-training#25]
Hi,
Setting ConfigServer  does not effect. 
In ConfigServer i set https://github.com/Pamir/azure-spring-config-demo.git with http basic authentication.
In the logs we see
```
2020-03-07 14:44:05.784  INFO 1 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : https://spring-cloud-lab.svc.azuremicroservices.io/config
2020-03-07 14:44:06.783 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed


java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:139) ~[spring-cloud-config-client-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:52) ~[spring-cloud-context-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locateCollection(ConfigServicePropertySourceLocator.java:154) ~[spring-cloud-config-client-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]

```

**Comment by Pamir** [comment]
You have to package your jar file with appropriate profile -Pcloud
